- name: Copy and Start Go on Linux Server
  hosts: webserver
  become: yes
  tasks:
    - name: Copy Go Binary
      copy:
        src: ../moroback
        dest: /home/ec2-user
        mode: "0755"

    - name: Start Go Application
      command: ./moroback